version: '3.9'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=psql
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - time_manager_network

  phoenix:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/psql
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: mix phx.server
    networks:
      - time_manager_network

  vue:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - phoenix
    command: npm run dev
    networks:
      - time_manager_network

volumes:
  pgdata:

networks:
  time_manager_network:
    driver: bridge